@DientesLimpios.API_HostAddress = http://localhost:5289/api/consultorios

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json

###
Post {{DientesLimpios.API_HostAddress}}
Content-type: application/json

{
    "nombre" : "Consultorio A"
}